<?php
declare(strict_types=1);

/**
 * =========================================================
 * CAHCET Faculty Leave Management System
 * Secure PDF Generator (FINAL – STABLE)
 * =========================================================
 */

error_reporting(0);
ini_set('display_errors', '0');

// Buffering to catch include whitespace
ob_start();

/* ---------------- REQUIRED FILES ---------------- */
require_once '../config.php';
require_once '../SimpleJWT.php';
require_once '../fpdf/fpdf.php';
require_once '../audit.php';

// Clean any accidental output from includes
if (ob_get_length()) ob_clean();

try {

    /* ---------------- AUTHENTICATION ---------------- */
    $token = JWT::get_bearer_token();
    if (!$token) {
        throw new Exception('Unauthorized', 401);
    }

    $user = JWT::decode($token);
    if (!$user) {
        throw new Exception('Invalid token', 401);
    }

    /* ---------------- INPUT VALIDATION ---------------- */
    $leaveId = isset($_GET['id']) ? (int)$_GET['id'] : 0;
    if ($leaveId <= 0) {
        throw new Exception('Invalid Leave ID', 400);
    }

    /* ---------------- FETCH LEAVE DATA ---------------- */
    $stmt = $conn->prepare(
        "SELECT l.*, u.name, u.role, u.department
         FROM leave_requests l
         JOIN users u ON l.user_id = u.id
         WHERE l.id = ?"
    );
    $stmt->execute([$leaveId]);
    $leave = $stmt->fetch(PDO::FETCH_ASSOC);

    if (!$leave) {
        throw new Exception('Leave request not found', 404);
    }

    /* ---------------- ACCESS CONTROL ---------------- */
    $canView =
        $user['id'] == $leave['user_id'] ||
        in_array($user['role'], ['admin', 'principal']) ||
        ($user['role'] === 'hod' && $user['department'] === $leave['department']);

    if (!$canView) {
        throw new Exception('Access denied', 403);
    }

    /* ---------------- FETCH SUBSTITUTIONS ---------------- */
    $stmt = $conn->prepare(
        "SELECT ls.*, u.name AS sub_name
         FROM leave_substitutions ls
         JOIN users u ON ls.substitute_user_id = u.id
         WHERE ls.leave_request_id = ?"
    );
    $stmt->execute([$leaveId]);
    $subs = $stmt->fetchAll(PDO::FETCH_ASSOC);

    /* ---------------- FETCH APPROVALS ---------------- */
    $stmt = $conn->prepare(
        "SELECT * FROM approvals WHERE leave_request_id = ?"
    );
    $stmt->execute([$leaveId]);
    $approvals = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $hodApproval = null;
    $principalApproval = null;

    foreach ($approvals as $app) {
        if ($app['role_at_time'] === 'hod') {
            $hodApproval = $app;
        }
        if ($app['role_at_time'] === 'principal') {
            $principalApproval = $app;
        }
    }

    /* ---------------- HELPER: SIGNER INFO ---------------- */
    function getSignerInfo(PDO $conn, ?array $approval): array
    {
        if (!$approval) return ['name' => '', 'signature_path' => null];

        $stmt = $conn->prepare(
            "SELECT name, signature_path FROM users WHERE id = ?"
        );
        $stmt->execute([$approval['approver_id']]);
        return $stmt->fetch(PDO::FETCH_ASSOC) ?: ['name' => '', 'signature_path' => null];
    }

    $hodInfo = getSignerInfo($conn, $hodApproval);
    $princInfo = getSignerInfo($conn, $principalApproval);

    /* ---------------- PDF CLASS ---------------- */
    class PDF extends FPDF
    {
        function Header()
        {
            $this->SetFont('Times', 'B', 14);
            $this->Cell(0, 6, 'C. ABDUL HAKEEM COLLEGE OF ENGINEERING & TECHNOLOGY', 0, 1, 'C');
            $this->SetFont('Times', '', 10);
            $this->Cell(0, 5, 'Melvisharam - 632 509', 0, 1, 'C');
            $this->Ln(3);
            $this->SetFont('Times', 'B', 13);
            $this->Cell(0, 6, 'LEAVE APPLICATION', 0, 1, 'C');
            $this->Ln(5);
            $this->Line(10, $this->GetY(), 200, $this->GetY());
            $this->Ln(6);
        }

        function Footer()
        {
            $this->SetY(-15);
            $this->SetFont('Times', 'I', 8);
            $this->Cell(0, 10, 'Generated by CAHCET Faculty Leave Management System', 0, 0, 'C');
        }
    }

    /* ---------------- CREATE PDF ---------------- */
    $pdf = new PDF();
    $pdf->SetMargins(15, 15, 15);
    $pdf->SetAutoPageBreak(true, 15);
    $pdf->AddPage();
    $pdf->SetFont('Times', '', 12);

    /* ---------------- BODY CONTENT ---------------- */
    $pdf->Cell(0, 8, 'Respected Sir,', 0, 1);

    $leaveType = $leave['leave_type'];

    if ($leave['duration_type'] === 'Hours') {
        $duration = $leave['selected_hours'] . ' Hour(s)';
        $dateStr = 'on ' . date('d-m-Y', strtotime($leave['start_date']));
    } else {
        $d1 = new DateTime($leave['start_date']);
        $d2 = new DateTime($leave['end_date']);
        $days = $d1->diff($d2)->days + 1;
        $duration = $days . ' Day(s)';
        $dateStr =
            'from ' . date('d-m-Y', strtotime($leave['start_date'])) .
            ' to ' . date('d-m-Y', strtotime($leave['end_date']));
    }

    $reason = preg_replace('/\s+/', ' ', trim($leave['reason']));

    $text = "Kindly grant me $leaveType leave for $duration $dateStr. Reason: $reason";
    $pdf->MultiCell(0, 7, $text);

    $pdf->Ln(8);
    $pdf->Cell(0, 8, 'Thanking you,', 0, 1);
    $pdf->Ln(15);
    $pdf->Cell(0, 8, 'Yours faithfully,', 0, 1);
    $pdf->Cell(0, 8, $leave['name'], 0, 1);

    /* ---------------- AUDIT ---------------- */
    logAudit($conn, $user['id'], 'PDF_DOWNLOAD', ['leave_id' => $leaveId]);

    /* ---------------- OUTPUT HEADERS ---------------- */
    header('Content-Type: application/pdf');
    header('Content-Disposition: inline; filename="Leave_Application_' . $leaveId . '.pdf"');
    header('Cache-Control: private, max-age=0, must-revalidate');
    header('Pragma: public');

    $pdf->Output('I');
    exit;

} catch (Throwable $e) {

    error_log('[PDF ERROR] ' . $e->getMessage());

    http_response_code(500);
    header('Content-Type: application/json');
    echo json_encode([
        'error' => 'PDF generation failed',
        'message' => $e->getMessage()
    ]);
    exit;
}
