<?php
// Disable output buffering to prevent corruption
if (ob_get_length()) ob_end_clean();
error_reporting(0); // Supress warnings
ini_set('display_errors', 0);

require_once '../config.php';
require_once '../SimpleJWT.php';
require_once '../fpdf/fpdf.php'; // Load manual FPDF
require_once '../audit.php';

// AGGRESSIVE ERROR SUPPRESSION for PDF
ob_end_clean(); // Clean any whitespace from includes
error_reporting(0);
ini_set('display_errors', 0);

// 1. Auth Check
$token = JWT::get_bearer_token();
$user = $token ? JWT::decode($token) : null;

if (!$user) {
    http_response_code(403);
    die("Unauthorized");
}

$leaveId = isset($_GET['id']) ? intval($_GET['id']) : 0;
if (!$leaveId) die("Invalid Leave ID");

// 2. Fetch Data
$stmt = $conn->prepare("SELECT l.*, u.name, u.role, u.department, u.email 
                        FROM leave_requests l 
                        JOIN users u ON l.user_id = u.id 
                        WHERE l.id = ?");
$stmt->execute([$leaveId]);
$leave = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$leave) die("Leave not found");

// Access Control
$canView = ($user['id'] == $leave['user_id']) || 
           ($user['role'] == 'principal') || 
           ($user['role'] == 'admin') || 
           ($user['role'] == 'hod' && $user['department'] == $leave['department']);

if (!$canView) die("Access Denied");

// Fetch Substitutions
$stmt = $conn->prepare("SELECT ls.*, u.name as sub_name 
                        FROM leave_substitutions ls 
                        JOIN users u ON ls.substitute_user_id = u.id 
                        WHERE ls.leave_request_id = ?");
$stmt->execute([$leaveId]);
$subs = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Fetch Approvals
$stmt = $conn->prepare("SELECT * FROM approvals WHERE leave_request_id = ?");
$stmt->execute([$leaveId]);
$approvals = $stmt->fetchAll(PDO::FETCH_ASSOC);

$hodApproval = null;
$principalApproval = null;
foreach($approvals as $app) {
    if ($app['role_at_time'] == 'hod') $hodApproval = $app;
    if ($app['role_at_time'] == 'principal') $principalApproval = $app;
}

// 3. Helpers to get names
// 3. Helpers to get names
function getSignerInfo($conn, $app) {
    if (!$app) return ['name'=>'', 'signature_path'=>null];
    $stmt = $conn->prepare("SELECT name, signature_path FROM users WHERE id = ?");
    $stmt->execute([$app['approver_id']]);
    $res = $stmt->fetch(PDO::FETCH_ASSOC);
    return $res ? $res : ['name'=>'', 'signature_path'=>null];
}
$hodInfo = getSignerInfo($conn, $hodApproval);
$princInfo = getSignerInfo($conn, $principalApproval);
$hodName = $hodInfo['name'];
$princName = $princInfo['name'];
$hodSigPath = $hodInfo['signature_path'];
$princSigPath = $princInfo['signature_path'];


// 4. PDF Generation using FPDF
class PDF extends FPDF
{
    function Header()
    {
        $this->SetFont('Arial','B',14);
        $this->Cell(0,5,'C. ABDUL HAKEEM COLLEGE OF',0,1,'C');
        $this->Cell(0,5,'ENGINEERING & TECHNOLOGY',0,1,'C');
        $this->SetFont('Arial','',10);
        $this->Cell(0,5,'Hbkeem Nagar, Melvisharam - 632 509.',0,1,'C');
        $this->Ln(5);
        
        $this->SetFont('Arial','BU',12);
        $this->Cell(0,10,'LEAVE APPLICATION',0,1,'C');
        $this->Ln(5);
    }

    function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Arial','I',8);
        $this->Cell(0,10,'Generated by Faculty Management System',0,0,'C');
    }
}

$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial','',12);

// --- Content Row 1: From / To ---
$yStart = $pdf->GetY();
$xLeft = 10;
$xRight = 110;

// Left Col (Applicant)
$pdf->SetXY($xLeft, $yStart);
$pdf->SetFont('Arial','B',11);
$pdf->Cell(80,5,'From',0,1);
$pdf->SetFont('Arial','',11);
$pdf->Cell(80,5,$leave['name'],0,1);
$pdf->Cell(80,5,'Assistant Professor',0,1); // Static as requested earlier
$pdf->Cell(80,5,'Department of '.$leave['department'],0,1);

// Right Col (To)
$pdf->SetXY($xRight, $yStart);
$pdf->SetFont('Arial','B',11);
$pdf->Cell(80,5,'To',0,1);
$pdf->SetFont('Arial','',11);
$pdf->Cell(80,5,'The Correspondent / Principal',0,1);
$pdf->Cell(80,5,'C. Abdul Hakeem College of Engg & Tech',0,1);
$pdf->Cell(80,5,'Melvisharam - 632 509.',0,1);

$pdf->SetY($yStart + 30); // Move down

// Through HoD
$pdf->Cell(30,8,'Through HoD:',0,0);
$pdf->SetFont('Arial','I',11);
$pdf->Cell(60,8, ($hodName ? $hodName : 'Pending Signature'), 'B', 0); // Underline effect
$pdf->SetFont('Arial','',11);
$pdf->Cell(70,8, 'Date: '.date('d-m-Y'), 0, 1, 'R');

$pdf->Ln(5);

// Sir
$pdf->Cell(0,8, 'Sir,', 0, 1);
$pdf->Write(7, 'Kindly grant me ');
$pdf->SetFont('Arial','B',11);
$pdf->Write(7, $leave['leave_type']);
$pdf->SetFont('Arial','',11);
$pdf->Write(7, ' leave for ');
$pdf->SetFont('Arial','B',11);

// Duration Calc
if ($leave['duration_type'] == 'Hours') {
    $dur = $leave['selected_hours'] . ' Hour(s)';
} else {
    $d1 = new DateTime($leave['start_date']);
    $d2 = new DateTime($leave['end_date']);
    $diff = $d1->diff($d2)->days + 1;
    $dur = $diff . ' Day(s)';
}

$pdf->Write(7, $dur);
$pdf->SetFont('Arial','',11);
$pdf->Write(7, ' on/from ');
$pdf->SetFont('Arial','B',11);
$pdf->Write(7, date('d-m-Y', strtotime($leave['start_date'])));
$pdf->SetFont('Arial','',11);
$pdf->Write(7, ' to ');
$pdf->SetFont('Arial','B',11);
$pdf->Write(7, date('d-m-Y', strtotime($leave['end_date'])));
$pdf->SetFont('Arial','',11);
$pdf->Write(7, '.');
$pdf->Ln(10);

$pdf->Write(7, 'Reason: ');
$pdf->SetFont('Arial','I',11);
$pdf->Write(7, $leave['reason']);
$pdf->Ln(12);

// Faculty Sign
$pdf->SetX(120);
$pdf->Cell(70, 5, 'Yours faithfully,', 0, 1, 'C');
$pdf->Ln(15);
$pdf->SetX(120);
$pdf->Cell(70, 5, '(Signature of Faculty)', 'T', 1, 'C'); // Line above text

$pdf->Ln(10);
$pdf->SetFont('Arial','B',11);
$pdf->Cell(0, 10, 'Class Arrangements Made:', 0, 1);

// Table Header
$pdf->SetFont('Arial','B',10);
$pdf->SetFillColor(240,240,240);
$pdf->Cell(30, 8, 'Date', 1, 0, 'C', true);
$pdf->Cell(20, 8, 'Hour', 1, 0, 'C', true);
$pdf->Cell(70, 8, 'Substitute (Faculty)', 1, 0, 'C', true);
$pdf->Cell(30, 8, 'Status', 1, 0, 'C', true);
$pdf->Cell(30, 8, 'Initials', 1, 1, 'C', true);

// Table Body
$pdf->SetFont('Arial','',10);
if (count($subs) > 0) {
    foreach($subs as $sub) {
        $pdf->Cell(30, 8, date('d.m.y', strtotime($sub['date'])), 1, 0, 'C');
        $pdf->Cell(20, 8, ($sub['hour_slot'] == 0 ? 'Full' : $sub['hour_slot']), 1, 0, 'C');
        $pdf->Cell(70, 8, $sub['sub_name'], 1, 0, 'L');
        
        $status = $sub['status'];
        if ($status == 'ACCEPTED') $pdf->SetTextColor(0,128,0);
        else $pdf->SetTextColor(128,0,0);
        
        $pdf->Cell(30, 8, $status, 1, 0, 'C');
        
        $pdf->SetTextColor(0,0,0);
        $pdf->Cell(30, 8, '', 1, 1, 'C'); // Initials box
     }
} else {
    $pdf->Cell(180, 8, 'No substitution required.', 1, 1, 'C');
}

$pdf->Ln(15);

// Digital Signatures
$ySig = $pdf->GetY();

// HoD Box
$pdf->SetXY(10, $ySig);
if ($hodApproval) {
    $pdf->SetDrawColor(0,128,0); // Green
    $pdf->SetLineWidth(0.5);
    $pdf->Rect(10, $ySig, 60, 25);
    
    $pdf->SetXY(10, $ySig+2);
    $pdf->SetTextColor(0,128,0);
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(60, 5, 'Digitally Recommended', 0, 1, 'C');
    
    // Check for Image
    if ($hodSigPath && file_exists('../'.$hodSigPath)) {
        // Embed Image
        $pdf->Image('../'.$hodSigPath, 15, $ySig+8, 50, 15);
        $pdf->SetXY(10, $ySig+25); // Move cursor below image
    } else {
        // Fallback to text
        $pdf->SetFont('Arial','I',14);
        $pdf->Cell(60, 10, $hodName, 0, 1, 'C');
    }
    
    $pdf->SetFont('Arial','',8);
    $pdf->SetTextColor(0,0,0);
    $pdf->Cell(60, 5, $hodApproval['created_at'], 0, 1, 'C');
} else {
    $pdf->SetDrawColor(0,0,0);
    $pdf->Rect(10, $ySig, 60, 25);
    $pdf->SetXY(10, $ySig+10);
    $pdf->Cell(60, 5, 'HoD Signature', 0, 0, 'C');
}

// Princ Box
$pdf->SetXY(130, $ySig);
if ($principalApproval) {
    $pdf->SetDrawColor(0,128,0); // Green
    $pdf->SetLineWidth(0.5);
    $pdf->Rect(130, $ySig, 60, 25);
    
    $pdf->SetXY(130, $ySig+2);
    $pdf->SetTextColor(0,128,0);
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(60, 5, 'Digitally Granted', 0, 1, 'C');
    
    // Check for Image
    if ($princSigPath && file_exists('../'.$princSigPath)) {
        // Embed Image
        $pdf->Image('../'.$princSigPath, 135, $ySig+8, 50, 15);
         $pdf->SetXY(130, $ySig+25);
    } else {
        $pdf->SetFont('Arial','I',14);
        $pdf->Cell(60, 10, $princName, 0, 1, 'C');
    }

    $pdf->SetFont('Arial','',8);
    $pdf->SetTextColor(0,0,0);
    $pdf->Cell(60, 5, $principalApproval['created_at'], 0, 1, 'C');
} else {
    $pdf->SetDrawColor(0,0,0);
    $pdf->Rect(130, $ySig, 60, 25);
    $pdf->SetXY(130, $ySig+10);
    $pdf->Cell(60, 5, 'Principal Signature', 0, 0, 'C');
}

$pdf->SetDrawColor(0,0,0);
$pdf->SetTextColor(0,0,0);
$pdf->SetY($ySig + 30);

// Labels
$pdf->SetX(10);
$pdf->Cell(60,5,'HEAD OF DEPT',0,0,'C');

$pdf->SetX(130);
$pdf->Cell(60,5,'PRINCIPAL',0,0,'C');


logAudit($conn, ($user['id'] ?? null), 'PDF_DOWNLOAD', ['leave_id'=>$leaveId]);

$pdf->Output();
?>
